name: Azure Static Web Apps CI/CD

description: Deploy Sarah Jones' Portfolio Website to Azure Static Web Apps

on:
  push:
    branches:
      - main  # Change to your branch if it's different
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2

      - name: Upload static files to Azure Static Web Apps
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # Used to authenticate with GitHub
          action: "upload"
          app_location: "/"  # Location of your app source code
          output_location: "/"  # Location of the built app content
